services:
- docker
script:
- echo "Performing in `pwd` with home: $HOME"
- export VERSION=$(date '+%Y.%m.%d.%H.%M')
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- if [ "x$DIAMOND_BASE64" = "x" ]; then echo "!!! NO LICENSE !!! Specify DIAMOND_BASE64 environment variable"; else echo $DIAMOND_BASE64 | base64 -d > $HOME/fpga/license.dat; fi
- if [ "x$DIAMOND_MAC" = "x" ]; then echo "!!! NO LICENSE !!! Specify DIAMOND_MAC environment variable"; export DIAMOND_MAC="00:11:22:33:44:55"; fi
- docker run --rm --mac-address=$DIAMOND_MAC -it -e LM_LICENSE_FILE=/fpga/license.dat -v $HOME/fpga:/fpga -v $HOME/dist:/dist -v `pwd`:/scripts dok3r/ulx3s-build /scripts/build.sh
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: ../dist/*
  skip_cleanup: true
  on:
    tags: true
